import { Box } from "@chakra-ui/layout";
import React from "react";
import {
	Table,
	Thead,
	Tbody,
	Tr,
	Th,
	Td,
	TableCaption,
	TableContainer,
	Text,
	Accordion,
	AccordionItem,
	AccordionButton,
	AccordionPanel,
	AccordionIcon,
} from "@chakra-ui/react";

type Props = {};

const TableCompare = (props: Props) => {
	return (
		<Box margin="20px 0">
			<Accordion
				allowToggle
				defaultChecked={true}
			>
				<AccordionItem border="none">
					<AccordionButton
						px="4"
						py="3"
						bgColor="bg.gray"
						_hover={{
							bgColor: "bg.gray",
						}}
					>
						<Text
							width="100%"
							textAlign="left"
							fontWeight="semibold"
							fontSize="md"
							color="text.black"
						>
							Bộ xử lý
						</Text>
						<AccordionIcon />
					</AccordionButton>
					<AccordionPanel padding={0}>
						<TableContainer>
							<Table>
								<Tbody>
									<Tr>
										<Td
											px="3"
											py="2"
											fontSize="sm"
											borderWidth="1px"
											borderColor="border.primary"
										>
											1
										</Td>
										<Td
											px="3"
											py="2"
											fontSize="sm"
											borderWidth="1px"
											borderColor="border.primary"
										>
											2
										</Td>
										<Td
											px="3"
											py="2"
											fontSize="sm"
											borderWidth="1px"
											borderColor="border.primary"
										>
											3
										</Td>
										<Td
											px="3"
											py="2"
											fontSize="sm"
											borderWidth="1px"
											borderColor="border.primary"
										>
											3
										</Td>
										<Td
											px="3"
											py="2"
											fontSize="sm"
											borderWidth="1px"
											borderColor="border.primary"
										>
											3
										</Td>
									</Tr>
									<Tr>
										<Td
											px="3"
											py="2"
											fontSize="sm"
											borderWidth="1px"
											borderColor="border.primary"
										>
											1
										</Td>
										<Td
											px="3"
											py="2"
											fontSize="sm"
											borderWidth="1px"
											borderColor="border.primary"
										>
											2
										</Td>
										<Td
											px="3"
											py="2"
											fontSize="sm"
											borderWidth="1px"
											borderColor="border.primary"
										>
											3
										</Td>
										<Td
											px="3"
											py="2"
											fontSize="sm"
											borderWidth="1px"
											borderColor="border.primary"
										>
											3
										</Td>
										<Td
											px="3"
											py="2"
											fontSize="sm"
											borderWidth="1px"
											borderColor="border.primary"
										>
											3
										</Td>
									</Tr>
									<Tr>
										<Td
											px="3"
											py="2"
											fontSize="sm"
											borderWidth="1px"
											borderColor="border.primary"
										>
											1
										</Td>
										<Td
											px="3"
											py="2"
											fontSize="sm"
											borderWidth="1px"
											borderColor="border.primary"
										>
											2
										</Td>
										<Td
											px="3"
											py="2"
											fontSize="sm"
											borderWidth="1px"
											borderColor="border.primary"
										>
											3
										</Td>
										<Td
											px="3"
											py="2"
											fontSize="sm"
											borderWidth="1px"
											borderColor="border.primary"
										>
											3
										</Td>
										<Td
											px="3"
											py="2"
											fontSize="sm"
											borderWidth="1px"
											borderColor="border.primary"
										>
											3
										</Td>
									</Tr>
								</Tbody>
							</Table>
						</TableContainer>
					</AccordionPanel>
				</AccordionItem>
			</Accordion>
		</Box>
	);
};

export default TableCompare;
